[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "hxse", email = "narutohy@163.com"},
]
dependencies = [
    "prompt-toolkit>=3.0.36",
    "pypinyin>=0.48.0",
]
requires-python = ">=3.10"
license = {text = "MIT"}
