
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "hxse", email = "narutohy@163.com"},
]
dependencies = [
    "packaging>=24.1",
    "feud>=0.3.2",
]
requires-python = ">=3.11"
license = {text = "MIT"}
